# Generated by Django 2.1.3 on 2018-12-14 09:32

from django.db import migrations, models
import restaurantes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=150)),
                ('alergenos', models.TextField()),
                ('precio', models.FloatField(validators=[restaurantes.models.validar_precio])),
            ],
        ),
    ]
